[package]
name = "mat3"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
material-colors = { version = "0.4.2", features = ["image",  "serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
